spring.application.name=notification-service

# Server
server.port=8080

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/capstone_db




spring.datasource.username=postgres
spring.datasource.password=2916
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JACKSON
# ===============================
spring.jackson.time-zone=UTC

# ===============================
# LOGGING (optional but useful)
# ===============================
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=saluvadisreekar111@gmail.com
spring.mail.password=znlagkbwnkjpgzep

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.account.sid=ACf54a89063dd9ed3853e35f1063088539
twilio.auth.token=c794c406b57891e0828cdce8d8bba393
twilio.phone.number=+12245041679